team_race_web_external:
    resource: "@TeamRaceWebBundle/Resources/config/routingExternal.xml"
    prefix:   /
    
team_race_web_user:
    resource: "@TeamRaceWebBundle/Resources/config/routingUser.xml"
    prefix:   /
    
team_race_web_teamrace:
    resource: "@TeamRaceWebBundle/Resources/config/routingTeamrace.xml"
    prefix:   /

