security:
    encoders:
        TeamRace\WebBundle\Entity\User:
            algorithm: bcrypt
            cost: 13
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: TeamRace\WebBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                check_path: loginCheck
                login_path: login
                default_target_path: userHome
            logout: ~
            anonymous: ~
           
    access_control:
        - { path: ^/(en|de)/user, roles: ROLE_USER }
        - { path: ^/(en|de)/teamrace, roles: ROLE_USER }