security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        TeamRace\WebBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: TeamRace\WebBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                check_path: loginCheck
                login_path: login
                default_target_path: userHome
            logout: ~
            anonymous: ~
           

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|de)/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|de)/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|de)/about$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|de)/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/languageSwitch/(en|de), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }